"""shared money pot schema

Revision ID: 10100fcc936e
Revises: 
Create Date: 2026-08-11 02:30:38.417727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10100fcc936e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('grocery_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('pot_id', sa.Integer(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pot_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'member')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pot_id', name='uq_membership_user_pot')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index('ix_membership_pot_role', ['pot_id', 'role'], unique=False)
        batch_op.create_index('uq_membership_one_owner_per_pot', ['pot_id'], unique=True, sqlite_where=sa.text("role = 'owner'"), postgresql_where=sa.text("role = 'owner'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index('uq_membership_one_owner_per_pot', sqlite_where=sa.text("role = 'owner'"), postgresql_where=sa.text("role = 'owner'"))
        batch_op.drop_index('ix_membership_pot_role')

    op.drop_table('membership')
    op.drop_table('grocery_item')
    op.drop_table('user')
    op.drop_table('pot')
    # ### end Alembic commands ###
